### ISSUE TITLE
HTTP chunked request is invalid

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/z-way-issues#102]
http://forum.z-wave.me/viewtopic.php?f=3422&t=22909

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/home-automation/issues/323

**Comment by PoltoS** [comment]
Moved: https://github.com/Z-Wave-Me/home-automation/issues/323

**Comment by bladerunner2020** [comment]
Have the same issue with bad chunked request...

**Comment by sja** [comment]
I think this should be prioritized, because all external tools which rely on the HTTP standard cannot use Z-Way anymore.

**Comment by thexperiments** [comment]
Also blocking me developing a plugin. Any updates?
This renders the API useless when interacting with newer node versions (most likely also other runtimes with decent http parsers).

**Comment by PoltoS** [comment]
We are updating mongoose right now to fix this issue.

Will be done in a week or so

**Comment by thexperiments** [comment]
Any update? Have not yet seen a new release

**Comment by PoltoS** [comment]
Please try this build v2.2.2-test-new-webserver (exists only for Raspberry Pi).

Some functions might not work. Please write here all bugs you see related to the new http server implementation: https://github.com/Z-Wave-Me/z-way-issues/issues/107

I close this issue to move in the latter one
