### ISSUE TITLE
Aeotec Smart Switch 6 recognized as dimmer instead of switch

### ISSUE THREAD

**Issue by bogri** [Z-Wave-Me/z-way-issues#104]
I have an Aeotec Smart Switch 6 (ZW096-C16) and after inclusion and interview it seem to be recognized as dimmer instead of switch. Going to the list of devices it is shown as a dimmer in the Smart Home UI. Don't know how much of the log you want, but I'm attaching the starting part, where I can see the device specific logs (device no 20). If you need more logs I can supply with more tracings.
[z-way-smartSW.txt](https://github.com/Z-Wave-Me/z-way-issues/files/188336/z-way-smartSW.txt)

**Comment by PoltoS** [comment]
Please see our fix on Aeotec site: https://aeotec.freshdesk.com/support/solutions/articles/6000102263-z-way-hack-to-make-the-smart-switch-6-work-as-a-on-off-switch
