### ISSUE TITLE
Issues wit upgrade script to v2.2.2

### ISSUE THREAD

**Issue by alexeyzimarev** [Z-Wave-Me/z-way-issues#105]
Current upgrade script produces start/stop loop at the end:

```
Starting z-way-server: done.
Starting z-way-server: done.
.
/etc/init.d/readKey: line 33: echo: write error: Invalid argument
Stopping z-way-server: done.
Thank you for using RaZberry!
root@rpi308:/home/pi# Starting z-way-server: done.
.
/etc/init.d/readKey: line 33: echo: write error: Invalid argument
Stopping z-way-server: done.
Starting z-way-server: done.
.
/etc/init.d/readKey: line 33: echo: write error: Invalid argument
Stopping z-way-server: done.
Starting z-way-server: done.
.
/etc/init.d/readKey: line 33: echo: write error: Invalid argument
Stopping z-way-server: done.
Starting z-way-server: done.
.
/etc/init.d/readKey: line 33: echo: write error: Invalid argument
Stopping z-way-server: done.
Starting z-way-server: done.
```

**Comment by alexeyzimarev** [comment]
After upgrading to the latest Raspbian, the `echo: write error` has disappeared, however the server stop-start still continues indefinitely.

**Comment by alexeyzimarev** [comment]
I have found this during the upgrade execution:

```
Start mongoose http server
ls: cannot access config/zddx/*.xml: No such file or directory
Usage: ./z-cfg-update <filename>
Starting z-way-server
Starting z-way-server: done.
Thank you for using RaZberry!
pi@rpi305 ~ $ Starting z-way-server: done.
.
Stopping z-way-server: done.
Starting z-way-server: done.
```

There the start-stop begins and never ends.

I tried to copy the old xml files from previous installation's zddx folder, but for some reason these files disappear after a couple of seconds:

```
pi@rpi305 /opt/z-way-server/config/zddx $ cp /opt/z-way-server_2016-05-16-20-54-33/config/zddx/*.xml ./
pi@rpi305 /opt/z-way-server/config/zddx $ ls
caca3496-DevicesData.xml  e3cf5646-DevicesData.xml
pi@rpi305 /opt/z-way-server/config/zddx $ ls
caca3496-DevicesData.xml  e3cf5646-DevicesData.xml
pi@rpi305 /opt/z-way-server/config/zddx $ ls
caca3496-DevicesData.xml  e3cf5646-DevicesData.xml
pi@rpi305 /opt/z-way-server/config/zddx $ ls
caca3496-DevicesData.xml  e3cf5646-DevicesData.xml
pi@rpi305 /opt/z-way-server/config/zddx $ ls
caca3496-DevicesData.xml  e3cf5646-DevicesData.xml
pi@rpi305 /opt/z-way-server/config/zddx $ ls
pi@rpi305 /opt/z-way-server/config/zddx $ ls
pi@rpi305 /opt/z-way-server/config/zddx $ ls
```

I have tried on two Pis and both times got the same result. Upgrade happened from different versions.

**Comment by PoltoS** [comment]
Please remove the /etc/init.d/readKey script as it contain a bug. We will fix it in next versions.

**Comment by pz1** [comment]
What is this **readKey** supposed to do at the cost of 20% CPU time on my Raspi 2 ? 

The fact that the script can be removed suggests it isn't that important/useful

**Comment by PoltoS** [comment]
This script was supposed to handle button press on the new RaZberry h/w. But apparently it had problems.

It was removed in next versions until we solve this.

**Comment by pz1** [comment]
Thanks for the clarification

**Comment by pz1** [comment]
@PoltoS 

> This script was supposed to handle button press on the new RaZberry h/w. But apparently it had problems.
> It was removed in next versions until we solve this.

This seems not correct! I just upgraded to the official 2.2.3 release, and noted that this nasty readKey is there again with all it nasty effects on cpu load

**Comment by PoltoS** [comment]
Ok, we will revise this again. @aivs will have a look after 25th

**Comment by pz1** [comment]
Well also good to see that Niels added a recipe how to delete readKey in his message to the Forum. Very much welcomed!

**Comment by 10der** [comment]
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected
cat: /sys/class/gpio/gpio4/value: No such file or directory
./readKey: line 58: [: -eq: unary operator expected

issue here
<------><------><------>if [ $(cat /sys/class/gpio/gpio4/value) -eq "0" ]; then

**Comment by PoltoS** [comment]
This is because  /sys/class/gpio/gpio4 is not present on your system. We have removed it completelly from installer tool

**Comment by 10der** [comment]
Thank you for your prompt reply.
