### ISSUE TITLE
New http/mongoose issues

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/z-way-issues#107]
- file upload seems not to work (restore in ExpertUI does not work)

**Comment by ronie-z-wave** [comment]
logged in as admin:

cannot save instances -> 401 (Unauthorized)

it works in v2.2.2

**Comment by PoltoS** [comment]
@ronie-z-wave Please test this: z-way-server-RaspberryPiXTools-v2.2.2-test-new-webserver-5-gba57763.tgz

**Comment by diemue** [comment]
The camara support in the new web server ist not very good. In a web browser (ZWay UI) i have a very slow motion. i have only every 5 - 10 seconds a screen refresh.
In the iphone app, i have no picture. When i choose the camera button, i can see only a white window - without any picture (WLAN connection)
Switching back to ZWay 2.2.2 camera works like expected.
Tested with FosCam Outdoor Cameras (FI9805W,FI8905W,FI9805E) profile.
Camera settings in ZWay:
http://xxx.xxx.xxx.xxx:80/cgi-bin/hi3510/mjpegstream.cgi?-chn=11
IP camera: Instar (IN-6001HD)
Raspberry 2 with kernel 4.4 and all OS updates.

**Comment by ronie-z-wave** [comment]
webif seems to work again with this version.

401 ... seems to be an UI problem ZWAYSession in header is undefined ... I've testet latest dev/master also the dist folders ... they all seems to be ok ... maybe wrong/older ui?

**Comment by ronie-z-wave** [comment]
![image](https://cloud.githubusercontent.com/assets/10545480/15466994/6ba5b6da-20dc-11e6-8098-a5f30bd535c7.png)

does this also happens on others?
seems that not all pages are effected

**Comment by thexperiments** [comment]
Any updates? 
I will need to change to node 4.4 which can't handle the "corrupted" headers from issues #102 and #323.

When is the official release scheduled?
Is there be a way for me to support you with some "beta" test?

**Comment by PoltoS** [comment]
@thexperiments You can check **v2.2.2-test-new-webserver-5-gba57763** version for compatibility with the nodejs and other functionality.

**Comment by thexperiments** [comment]
Ok. If I get it right I can install it via.
`wget -q -O - http://razberry.z-wave.me/install/v2.2.2-test-new-webserver-5-gba57763  | sudo bash`

**Comment by PoltoS** [comment]
Correct!
Or use 8084 as usually and enter version name.

**Comment by PoltoS** [comment]
Selecting XML is not working: https://github.com/Z-Wave-Me/ExpertUI/issues/191#issuecomment-223157541

**Comment by cmolnar65** [comment]
Your solution worked. Updated to 2.2.2 now without the -test-server.

**Comment by PoltoS** [comment]
Please test version v2.2.2-test-new-webserver-8-ga9cd319 that fixes LoadXMLFile (Select Device Description) problem

**Comment by ronie-z-wave** [comment]
I'm not able to save modules - response 401 for POST api/v1/instances. 
But I'm logged in with admin user ...

**Comment by PoltoS** [comment]
@ronie-z-wave latest v2.2.2-test-new-webserver-8-ga9cd319 ?

**Comment by ronie-z-wave** [comment]
jup, not sure if I'm the only one who reports that,
it happens if you wan't to add a new module for example ...

de-/activate an instance isn't touched by this and works fine

**Comment by PoltoS** [comment]
Shall I close it?

**Comment by thexperiments** [comment]
Think it's fixed yes

2017-01-27 0:21 GMT+01:00 Poltorak Serguei <notifications@github.com>:
