### ISSUE TITLE
Aeon Labs Multisensor parameters broken

### ISSUE THREAD

**Issue by alexeyzimarev** [Z-Wave-Me/z-way-issues#108]
In some version after 2.0 setting bitset parameters for Aeon Labs Multisensor were broken.

There are three parameters that allow to define, which data is sent automatically for specific timing groups. It was possible to set these values before. After I had to reinstall the whole thing when upgrading to 2.2.2, these parameters were lost and I cannot set it again. Essentially, the sensor only reports motion data and temperature, humidity and light sensors do not report back, I can only update it manually. The UI says that the parameter type is "Bitset" and does not allow to enter anything there:

![2016-05-20_20-17-33](https://cloud.githubusercontent.com/assets/2821205/15437610/6b0e7434-1ec8-11e6-8fb8-3b4c3e18dc4d.png)

**Comment by PoltoS** [comment]
Duplicate to https://github.com/Z-Wave-Me/ExpertUI/issues/50
