### ISSUE TITLE
Camera support in new web server

### ISSUE THREAD

**Issue by diemue** [Z-Wave-Me/z-way-issues#109]
The camara support in the new web server ist not very good. In a web browser (ZWay UI) i have a very slow motion. i have only every 5 - 10 seconds a screen refresh. 
In the iphone app, i have no picture. When i choose the camera button, i can see only a white window - without any picture (WLAN connection)
Switching back to ZWay 2.2.2 camera works like expected.
Tested with FosCam Outdoor Cameras (FI9805W,FI8905W,FI9805E) profile.
Camera settings in ZWay:
http://xxx.xxx.xxx.xxx:80/cgi-bin/hi3510/mjpegstream.cgi?-chn=11
IP camera: Instar (IN-6001HD)
Raspberry  2 with kernel 4.4 and all OS updates.

**Comment by PoltoS** [comment]
@diemue why have you closed the issue?

**Comment by PoltoS** [comment]
Moved into #107
