### ISSUE TITLE
Different values. ZWaveAPI vs Expert UI

### ISSUE THREAD

**Issue by bogri** [Z-Wave-Me/z-way-issues#113]
Using the API to get values for Multichannel Association according to

ZWaveAPI/Run/devices[11].instances[0].commandClasses[142].data[1]

and then comparing to the values for "nodesInstances" shown in Expert UI (Expert Commands -> MultiChannelAssociation) are different? But if there's only one value like in value:[1] it looks like the same is shown in both alternatives.
![z_api](https://cloud.githubusercontent.com/assets/17220050/16569199/c8b6a910-4233-11e6-9201-e2affd2961fc.png)
![z-eui](https://cloud.githubusercontent.com/assets/17220050/16569200/c8d42706-4233-11e6-9c23-b5f4ec0c9642.png)

**Comment by PoltoS** [comment]
Please explain again. I've not got.

nodesInstances is an array of pairs node1, inst1, node2, inst2,....

While nodes gives you dirrect associations (A, not MCA)

**Comment by bogri** [comment]
Aha, sorry for the confusion. Didn't realize nodeInstances was an array of pairs (is there a good doc on this?).
Though, the ZWaveAPI shows that Group 1 doesn't have anything stored in nodeInstances (value:[]), while the Expert UI shows (1,1)?

**Comment by bogri** [comment]
Some more info. There's something "inconsistent" in the behaviour, IMHO. To reproduce:

Step 1. set the MCA (group=3, node=1, instance=1) through ZWaveAPI according to
`:8083/ZWaveAPI/Run/devices[11].instances[0].commandClasses[142].data[3].nodesInstances.value=[1]`

S 2. verify in log it's set
`[2016-07-05 22:11:09.434] [D] [zway] SETDATA devices.11.instances.0.commandClasses.142.data.3.nodesInstances = byte[1]`
`[2016-07-05 22:11:09.434] [D] [zway]   ( 01 )`

S 2a. call the API again
`:8083/ZWaveAPI/Run/devices[11].instances[0].commandClasses[142].data[3].nodesInstances`
shows
`{"invalidateTime":1467749191,"updateTime":1467749469,"type":"binary","value":[1]}`

S 3. check the Expert UI-> Configuration -> Expert commands and pressing button MultiChannelAssociation for instance 0 and pop-up window shows:
`3: None (22:06)`
`max: 16 (22:06)`
`nodes: 1 (04.07.2016)`
`nodesInstances: 1 (22:11)`

S 4. On the same page in Expert UI enter "3" for Group and press button Get and log suddenly shows
`[2016-07-05 22:15:55.455] [D] [zway] SETDATA devices.11.instances.0.commandClasses.142.data.3.nodesInstances = byte[0]`
`[2016-07-05 22:15:55.455] [D] [zway]   ( zero-length buffer )``

S 5. redo the step 3 and the result is suddenly different:
`3: None (22:15)`
`max: 16 (22:15)`
`nodes: 1 (04.07.2016)`
`nodesInstances:  (22:15)`

So the "Get" seem to reset the value for nodesInstances.

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/Z-Way-Manual/blob/master/includesDev/commandclasses_autodoc.tex#L550 

----- Исходное сообщение -----

**Comment by PoltoS** [comment]
You are really misusing the API. Doing data[3].nodesInstances.value=[1] will not result in sending Set command, but will change local copy of device's data. Please use .Set command!!!! 

----- Исходное сообщение -----

**Comment by bogri** [comment]
Using the Set command was the first thing I tried (which I have already mentioned in another issue)!!! But since it did not work from the API or Expert UI, I tried to find another solution, which apparently was totally wrong.
Thanx for the link to doc (looks like I had an old version of 2.0.1, where this info was missing).
