### ISSUE TITLE
Identification fails with third party USB sticks

### ISSUE THREAD

**Issue by yene** [Z-Wave-Me/z-way-issues#116]
The USB sticks:
- Z-Stick Series 2
- Z-Stick Gen5
- SIGMA Z-Wave Static Controller UZB EU

could not identify _Fibaro Motion Sensor FGMS-001 EU v2.7_ and other z-wave hardware correctly.

**Comment by PoltoS** [comment]
RaZberry builds do work with Z-Wave.Me RaZberry or UZB only. Aeotec not Sigma dongles are not supported
