### ISSUE TITLE
Z-Way stores username and password in cleartext in rememberme cookie

### ISSUE THREAD

**Issue by kvolden** [Z-Wave-Me/z-way-issues#118]
Z-Way actually stores the user's credentials in cleartext – both the username and the password – in a cookie when selecting "Remember me" on login.

This is seriously not good from a security standpoint. The standard and sane way of doing persistent sessions is to store the session id, not the complete login credentials of the user. Extracting the username and password client side is now as easy as getting the client to run "JSON.parse(decodeURIComponent(document.cookie.split(';')[3]).split('=')[1])".

You should fix this issue by only saving the session id, and probably do a security update fairly quickly.

**Comment by PoltoS** [comment]
Fixed a long time ago
