### ISSUE TITLE
Fibaro Relay Switch FGS 223 - Power monitoring not supported by Z-Way

### ISSUE THREAD

**Issue by TS-Tec** [Z-Wave-Me/z-way-issues#119]
Hello,

the new Fibaro Relay Switch FGS-223 (2x 1,5kW) now supports power monitoring for both channels.

Unfortunatly it seems that Z-Way currently only supports the power monitoring of the first channel. The second channel does not appear after device inclusion.

Same as many Fibaro devices, the Interview of the FGS223 was not completed. Maybe this is also a reason.

I hope this device will be supported fully with the next Z-Way releases...

Never the less: Thanks for the great work to all developers!

**Comment by PoltoS** [comment]
Fixed in latest RC. Will be released soon in 2.3.0
