### ISSUE TITLE
App Link other Z-Way controller: Does not seem to import sensor type information

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/z-way-issues#121]
The call _/ZAutomation/api/v1/namespaces/devices_sensorBinary_ returns sensortype "none" for the Remote Fibaro Universal binary sensors. If retrieved locally, they are classified as expected under "general_purpose". I haven't looked at other devices, but it seems that the type information is not retrieved by the App **Link other Z-Way controller**

![none](https://cloud.githubusercontent.com/assets/7747627/21010111/a02b2c22-bd4a-11e6-8423-c4c726bf600f.PNG)

**Comment by PoltoS** [comment]
Should go to https://github.com/Z-Wave-Me/home-automation

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/home-automation/commit/3c2bbf0b7a8eb9aba6aa11e3bac104925b0484ca
