### ISSUE TITLE
Support - User isn't able to remove ghost nodes

### ISSUE THREAD

**Issue by ronie-z-wave** [Z-Wave-Me/z-way-issues#122]
He tries the following things:
* Reset via SH-UI
* Reset via E-UI
* new installation of zway
* marking them as failed to remove them (doesn't work)

After controller factory default the controller starts counting on #18 instead of #2  

He's using:
* latest zway 2.3.0
* UZB 5.06

Some ideas?

**Comment by PoltoS** [comment]
May be EEPROM is damaged. Does it save newly added devices after reboot?

Can he do Factory default in EUI ? Does not help? Do HomeID changes in this? What is HomeID?

**Comment by ronie-z-wave** [comment]
He can do a factory reset in EUI but it don't solve the problem ... I'll forward your questions.
