### ISSUE TITLE
Support for multipress actions on NodOn 

### ISSUE THREAD

**Issue by bogri** [Z-Wave-Me/z-way-issues#123]
The manual for NodOn Soft Remote states:

> When  the  selected  profile  is  «SCENE»  (default  value),  the  Soft  Remote 
> communicates only with the home automation gateway. The user interface of your 
> gateway will then allow you to set-up scenes based on which (and which way) you 
> press the different buttons. To do so, please refer to your gateway’s user guide.
> The different actions that can be handled by the Soft Remote are:
> • Simple press (on I, O, P or M) 
> • Double press (on I, O, P or M) 
> • Long press (on I, O, P or M)
> • Button released (on I, O, P or M) 

but I can't find that the UI has support for this when configuring a scene. Is that correct? Only "simple press" is possible.
Z-Way: v2.2.4

**Comment by ronie-z-wave** [comment]
there is multipress support in v2.3.0 and higher
