### ISSUE TITLE
POPP Z-Wave Wall Plug Switch not working

### ISSUE THREAD

**Issue by pepuscz** [Z-Wave-Me/z-way-issues#131]
The interview process never finishes, even if forcing single interview results.

It is successfully detected as: Binary Power Switch

It detects following command classes:
Basic • SwitchBinary • SwitchAll • Configuration • ManufacturerSpecific • Protection • NodeNaming • Association • Version • Indicator •

However only command class Configuration finishes, the other never succeed.

**Comment by jpaana** [comment]
I also have a Popp Wall Plug Switch, outdoor version and its on/off switching functionality works, but power metering only shows 0W and 0Wh regardless. Following classes are detected: Basic • SwitchBinary • SwitchAll • Meter • AssociationGroupInformation • DeviceResetLocally • ZWavePlusInfo • Configuration • ManufacturerSpecific • PowerLevel • Protection • FirmwareUpdate • Association • Version • Indicator • MultiChannelAssociation • Security •
