### ISSUE TITLE
Device Inclusion error in Z-Way using WD MyCloud EX2 Ultra

### ISSUE THREAD

**Issue by sunilphilip14** [Z-Wave-Me/z-way-issues#140]
Hi,

I tried to include a device in Expert UI, but it says 'Unable to update data. controller.AddNodeToNetwork(1)'. It is throwing a 500 Server Error. Exclusion works fine.

![image](https://user-images.githubusercontent.com/37108265/37148312-256a8088-231e-11e8-9d39-f46873de6fd1.png)

**Comment by PoltoS** [comment]
This looks like missing licesne in the UZB1
