### ISSUE TITLE
Qubino Smart meter ZMNHTD1 failed interview

### ISSUE THREAD

**Issue by dvd2000k** [Z-Wave-Me/z-way-issues#141]
Qubino smart meter fail interview (Command Meter not finalized).
Also tried 2.3.7 rc7, issue persist.

Is there a solution to get it working?

**Comment by PoltoS** [comment]
Please see a temp solution here:
https://forum.z-wave.me/viewtopic.php?f=3419&t=26154&hilit=qubino&start=10#p73337

This is a Smart Meter device bug
