### ISSUE TITLE
Zway crashes instantly on WD Systems if Mobile App Support is running

### ISSUE THREAD

**Issue by LeoGr13** [Z-Wave-Me/z-way-issues#142]
Hi,
im using 2.3.6. beta on WD PR4100. If i have a instance of Mobile App Support running, the server instantly crashes. This bug was also in previous versions present. Without the UZB connected to the NAS, the server is no longer crashing.
Old app (find.z-wave.me connection) is working without any problem.
Thanks

**Comment by PoltoS** [comment]
Duplicate https://github.com/Z-Wave-Me/z-way-issues/issues/146
