### ISSUE TITLE
Razberry problems with ZWay Server 3.0.1

### ISSUE THREAD

**Issue by tengelmeier** [Z-Wave-Me/z-way-issues#154]
Hi, 

I reinstalled my whole working Raspberry installation with buster zway server 3.0 -  the upgrade to buster as described on the home page ran out of SD card memory and I ended with a broken installation.

Since the upgrade, my devolo switch is not visible in the regular interface any more. 
It can not complete the interview - something that never worked, it did never finish the security section, but the switch worked and was visible in the UI with older versions.

In the Expert UI I see:
- the Razberry daughter board is displayed as "Wireless activity: The device seems to dead" (but it works fine). Firmware is "SDK version 4.54.01", Application version "0.0"

- the devolo switch reports "Application version 1.10", SDK version 6.51.00, 
the interview stalls in the security section with the info

`/: None (12:04)
    supported: true (12:04)
    version: 1 (12:04)
    security: false (12:04)
    interviewDone: false (12:04)
    interviewCounter: 0 (12:22)
    scheme: 0 (12:04)
    secureNodeInfoFrame: (12:04)
    securityAbandoned: false (12:04)
    canStream: false (12:04)
    toFollow: None (12:04)`

- how can I restore the older behavior, i.e. expose an device when the interview is not completed? 
- How can I upgrade the Razberry daughter board (old version) to a latest supported firmware?
- is there any way to get a later devolo firmware and upgrade?

**Comment by tengelmeier** [comment]
Update: After re-inclusion of the devolo switch it appeared in the regular UI. Still wondering how to upgrade the two zwave firmware(s).

**Comment by PoltoS** [comment]
You have the latest supported firmware for the 3rd gen Z-Wave chip. For newer upgrades you need a new h/w with the new chip.
