### ISSUE TITLE
Server not starting after update to 3.0.5

### ISSUE THREAD

**Issue by simb0** [Z-Wave-Me/z-way-issues#155]
I use the Razberry with openhabian.

After the update the server was down. There were no errors during the installation, but I noticed that the start script is missing in /etc/init.d/.

When I try to start the server manually via 

sudo LD_LIBRARY_PATH=./libs ./z-way-server -l 0

No error, no log is written:

Z-Way version v3.0.5 from 2020-04-03 23:24:31 +0300 (build 94eb5f8e71b5007e49c3dc96da20dd5535c4c10d)
Looking for modules in ./modules
Module modinstaller.so loaded
Module modskininstaller.so loaded
Module moddhs.so loaded
Module modhttp.so loaded
Module modnotification2ext.so loaded
Module modhomekit.so loaded
Module modcrypto.so loaded
Module modenocean.so loaded
Module modzbw.so loaded
Module modiconinstaller.so loaded
Module modzwave.so loaded
Module modsockets.so loaded
Module modws.so loaded
Using default configuration file config.xml
Warning: failed to load external entity "config.xml"

>> I U 1
>> First free 0x307860
> Occupancy 1

How can i find out what is wrong?

**Comment by PoltoS** [comment]
Please try this solution:
sudo apt-get --reinstall install -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confold" -y z-way-server

**Comment by simb0** [comment]
That worked! I owe you a beer.
