### ISSUE TITLE
z-way-server 3.1.2 is missing from repository

### ISSUE THREAD

**Issue by gongtao0607** [Z-Wave-Me/z-way-issues#160]
z-way-server version 3.1.2 is in the pool/, but not in buster/main/binary-armhf/Packages (Although the timestamps indicate they are updated together)

Similar issue in UI, `Firmware update' page shows 3.1.2 changelog, but the latest version is still 3.1.1

**Comment by PoltoS** [comment]
Thanks, we are working on the fix.

**Comment by PoltoS** [comment]
This is fixed now.
