### ISSUE TITLE
Issues with Fibaro RGBW controller

### ISSUE THREAD

**Issue by scyto** [Z-Wave-Me/z-way-issues#163]
I am having issues with this controller.

It seems interviewing doesn't complete for the color switch, this means that it usually doesn't discover all the color switch target / current values.  in zwave me it seems to hang at this 91% stage.

I have reproduced this on both z-waveme and with zwavejs2mqtt as such this makes me guess that the issue is between the razberry zwave module and the rgbw controller.

I am unable to find a link to updated firmware (i have asked fibaro and I am still waiting).

![image](https://user-images.githubusercontent.com/11369180/106826483-dbb35a00-663b-11eb-9f01-35d4d8d1a931.png)

**Z-Way version** v3.1.2 from 2020-12-31 05:19:46 +0300 (build 01dab053dab281bda7c4e1863d63270993e78f00)

**Pi Version**
/bin/ls: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=67a394390830ea3ab4e83b5811c66fea9784ee69, stripped
Linux pi-zwave01 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

**Comment by scyto** [comment]
log 
[z-way-server.zip](https://github.com/Z-Wave-Me/z-way-issues/files/5922445/z-way-server.zip)

**Comment by PoltoS** [comment]
It's a device bug. Z-Way asks for channel 2, while RGBW answers with channel 3. Same for other channels.

[2021-02-03 16:49:43.387] [W] [zway] Reply not received before timeout for job (SwitchColor State Get)
[2021-02-03 16:49:43.387] [D] [zway] SENDING (cb 0x39): ( 01 0A 00 13 0B 03 33 03 **02** 25 39 C0 )
...
[2021-02-03 16:49:43.475] [D] [zway] RECEIVED: ( 01 0E 00 04 00 0B 04 33 04 **03** FF B3 00 01 03 80 )
...
[2021-02-03 16:49:43.476] [D] [zway] SETDATA devices.11.instances.0.commandClasses.51.data.**3**.level = 255 (0x000000ff)
...
[2021-02-03 16:49:45.564] [W] [zway] Reply not received before timeout for job (SwitchColor State Get)

**Comment by scyto** [comment]
thanks i have a new firmware coming today, will try that

**Comment by scyto** [comment]
closing as that device failed on me totally, I think it has been bad for a while.
