### ISSUE TITLE
Transfering system to docker

### ISSUE THREAD

**Issue by perhusaas** [Z-Wave-Me/z-way-issues#164]
as mentioned here: https://forum.z-wave.me/viewtopic.php?f=3425&t=33937

So, I made the docker, but i'm struggling with transferring my system to it.

I tried to copy the /config/ folder to the docker volume, but that doesn't contain info about logon details or room configuration. Can someone help me with getting all necessary info in to run it in the docker? Or perhaps which folders in host that needs a bind?

**Comment by PoltoS** [comment]
config/zddx/*
automation/storage

There are few others but less important

**Comment by perhusaas** [comment]
That works perfect, its now transferred to docker with 3.1.3. Thanks!

If i understand it right, i can now build a new image next time there is an update, and just link to these volumes? 
That wouldn't work if some files in this folder is a part of the update..
