### ISSUE TITLE
Improved handling of erratic measurments

### ISSUE THREAD

**Issue by jteg68** [Z-Wave-Me/z-way-issues#168]
Hi,

earlier I have seen from time to time incorrect temperature measurements in the log, but not often. With a new repeater that also reports temperature and humidity I get several per day. Using the data in a trend is then not useful as the spikes destroys the scaling. Example from the log today:
09:20   [Förstärkare : 181119482.2262784 °C]

Suggestion: add checks in the communication layer for impossible values. For example an acceptable range, and ignore data outside the range.

**Comment by PoltoS** [comment]
It might be an interesting idea to add such a range (min/max), but better to fix the RF issue causing this as a mangled multisensor value is a sign of a clear problem that can also lead to missed/dropped alarm signal which might be much more critical

**Comment by PoltoS** [comment]
Also use Security S0 or S2 with your sensors, and all RF mangled packets will be rejected automatically. For non-secure devices make sure to buy devices supporting CRC16 - it also increases the quality of checks for mangled packets.

**Comment by PoltoS** [comment]
Summary:
Won't fix as this is not fixing the root of your problem, but only one small subsequence.
Improve the RF quality (buy a RaZberry 7 Pro) or use Security S0/S2 or CRC16 to fix it.
