### ISSUE TITLE
Z-way server crash with aeon lab 4 in 1 sensor interview

### ISSUE THREAD

**Issue by alibab** [Z-Wave-Me/z-way-issues#2]
Hi,
Since update to 1.7 RC1 version, my z-way server crach when i do http request to interview sensorMultilevel. ( commandClass 49)
Can you help me ?
here is the full log file: 
https://dl.dropboxusercontent.com/u/77048016/z-wayLog.txt
Thk in advance

**Comment by pieceofsummer** [comment]
You're probably upgrading from some rather old version of Z-Way. In recent versions we've changed the data type used inside SensorMultilevel to support more sensor types, but your saved configuration file (from previous version) holds the old data.

Just force re-interview the device to get rid of the problem.

**Comment by alibab** [comment]
Hi,
Thk for your reply.
I've  come From version 1.5 RC3.
Force the re-interview have the same issue.
Request NIF too.
Must I exclude the device and re-include it?

**Comment by pieceofsummer** [comment]
If you don't have security devices, you may just stop z-way-server, delete configuration file config/zddx/xxxxxxxx-DevicesData.xml (where xxxxxxxx is your Home ID) and restart z-way-server. 
Re-including the device also works.

**Comment by alibab** [comment]
Hi,
I've rename the extension file ( xml.old).
I 've the same pb.
I 'll re-include the device in 2 day ( i can't now) and  ll come back to you.
Thk in advance.

**Comment by pieceofsummer** [comment]
You probably haven't stopped z-way-server before renaming the file. It rewrites it on stop.

Or just do the following: 
open that file with a text editor and find the following (in xpath syntax): `/devicesData/device[@id=15]/instance[@id=0]/commandClass[@id='0031']/data[@name='typemask']`
and delete that line.

Once again, it should be done with _stopped_ z-way-server

**Comment by alibab** [comment]
oups... :)
i've now stop the server , delete the file and re-start the server.
I've made a request NIF for all devices, just wait, but all seem ok for the moment.
Thank for your help.
