### ISSUE TITLE
Добавить UUID и хоть какую криптографию в JS функции

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/z-way-issues#22]

**Comment by pieceofsummer** [comment]
А поподробнее? Какой uuid, какую криптографию, зачем?

**Comment by PoltoS** [comment]
для OAuth

**Comment by r3b-fish** [comment]
криптографию для генерации токенов
uuid для генерации id токенов и id пользователей
uuid v4 будет достаточным
