### ISSUE TITLE
Обновление прошивки через <raspi-host-ip>:8084

### ISSUE THREAD

**Issue by chorus12** [Z-Wave-Me/z-way-issues#24]
Добрый день!
При обновлении прошивки через админ-консоль <raspi-host-ip>:8084 и указании конкретного релиза - например, v2.0.1-rc11 - система всё равно обновляет до последнего релиза, т.е. на текущий момент - до v2.0.0
Удобно было бы перед нажатием кнопки "Обновить" дополнительно показывать до какой версии будет выполнено обновление и запрашивать подтверждение.

**Comment by PoltoS** [comment]
просто не был кружочек переставлен. Это мы уже поправили: теперь кружок переставляется при вписывании конкретной версии в текстовом поле
