### ISSUE TITLE
no full interview of Fibaro Wall Plug FGWPE-101

### ISSUE THREAD

**Issue by mennobos** [Z-Wave-Me/z-way-issues#39]
I use Razberry with the different z-way versions, currently v2.0.1-rc14,  for 3/4 of a year or so, and with the different versions I have NOT been able to have a complete interview on my Fibaro Wall Plug FGWPE-101. And yes, I treid all the various resets as per Fibaro manual etc.
However the application (openHAB) works in principle fine. 
The '+' s I am missing are the 2nd and 6th ones.
If you need more info, let me know.

Just as a remark: when Configuring, and choosing 'Select Device Description' ... an alphabetic sorting would be appreciated ;)

Thanks!

**Comment by pieceofsummer** [comment]
What command classes are not passing interview? "2nd and 6th" is not very informative.

In "select device description" devices are sorted by matching score, best matches first.

**Comment by mennobos** [comment]
thx for you prompt reply!
Checked (after the new openHAB install gave me the same WARN) at the "InterView Results" window in Z-way ... all commandclasses are green checked exept the 'AlarmSensor commandclass' ...
And therefor 'Device interview stage is not complete' notification is displayed.
I tried to force interview in this window again, but no result.
I also understand not why my openHAB functioned well, I currently do not use the AlarmSensor class (I will in the future btw.)

Regarding sorting:
- I agree WHEN z-way finds the node correct, sorting on relevance is ok or perhaps better even auto inclusion 
- my experience is that unfortunately z-way does not always find Devicename of the nodes and than it is a complete NON-sort ... 

Anyhow thanks!!

**Comment by pieceofsummer** [comment]
Alarm Sensor interview is marked as done after receiving supported report. Please provide the log from the moment you press re-interview button for this particular command class.

**Comment by PoltoS** [comment]
This is a known problem of this device. It dies not support AlarmSensor, while announce it as supported. Just ignore the problem. It does not harm.

**Comment by reitermarkus** [comment]
Hi, I'm having the same problem with my Fibaro Univeral Binary Sensor FGBS-001. It's also not completing the `AlarmSensor` interviews.

@PoltoS, does what you said also apply for this device?
