### ISSUE TITLE
Если интервью до конца не пройдено и перезагрузить сервер, интервью становится не пройденным полностью

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/z-way-issues#41]
Если устройство не прошло до конца интервью, например RGBW не проходит два пункта, то после перезапуска контроллера все пункты интервью становятся не пройденными.

**Comment by PoltoS** [comment]
Действительно мы не сохраняем XML при незаконченном interview. Можно было бы по _zway_device_is_interview_failed проверять и сохранять, но вопрос, в какой момент и как пометить, что мы уже сохранили.

**Comment by aivs** [comment]
через 2 минуты после начала включения можно проверить и сохранить
