### ISSUE TITLE
Fahrenheit setting has no effect

### ISSUE THREAD

**Issue by jensmoes** [Z-Wave-Me/z-way-issues#49]
If I set the Fahrenheit to 1 in Defaults.xml like this:

``` xml
                <SensorMultilevel>
                        <Fahrenheit>1</Fahrenheit><!-- Default scale to use -->
                </SensorMultilevel>
                <ThermostatSetPoint>
                        <Fahrenheit>1</Fahrenheit><!-- Default scale to use -->
                </ThermostatSetPoint>
```

the sensors still show degrees celsius

**Comment by PoltoS** [comment]
Please show part of log when you do ThermostatSetpoint Get and get the Report. It should show scale = 1, deviceScale = 1 and no conversion between (if your device reports in F)

**Comment by jensmoes** [comment]
I do not have access to a thermostat at the moment but I believe the basic
issue is that virtual devices, such as the ones in the various existing
modules and any SensorMultiLevel vDev's I have tried to create myself does
not obey:

```
            <SensorMultilevel>

                    <Fahrenheit>1</Fahrenheit><!-- Default scale to use
```

-->

```
            </SensorMultilevel>

            <ThermostatSetPoint>

                    <Fahrenheit>1</Fahrenheit><!-- Default scale to use
```

-->

```
            </ThermostatSetPoint>
```

from Defaults.xml.

I would expect if I set deviceScale to the opposite (0 in this case) in a
vDev that the presented values would be converted from the device values
based on the settings in Defaults.xml

This is not the case neither in the http interface, the smarthome UI nor
the mobile apps.

**Comment by PoltoS** [comment]
Please try with this fix: https://github.com/Z-Wave-Me/home-automation/commit/9a50c550d3919c9d3f554417b09ca644aed6148f

**Comment by silverhack77** [comment]
I think I am still finding the same problem (using v 2.2.1)
See details at  https://forum.z-wave.me/viewtopic.php?f=3419&t=23318

using /ZWaveAPI/   shows correct units
using /ZAutomation/  does not.
