### ISSUE TITLE
v2.0.1 - selecting device description broken

### ISSUE THREAD

**Issue by alexeyzimarev** [Z-Wave-Me/z-way-issues#54]
I just upgraded Z-Way to 2.0.1 on RPi and found out that selecting a device description file does not work. If the description was not selected before, nothing happens at all. If there was a description file selected already and I try to select another one or the same one - all settings get reset and configuration page reports "device has no configuration". This is a major issue, I am now forced to stop any configuration at all because it just breaks everything.

**Comment by alexeyzimarev** [comment]
I reverted the version 2.0.0 and now Configuration tab is not even opening at all.

**Comment by PoltoS** [comment]
Was fixed in 2.0.2-rc1

**Comment by shrikantlahase** [comment]
i bought UZB  Z-WAY stick along with that i got one key as "ticket to smarthome"
where to use that key.....?  and How....?

**Comment by PoltoS** [comment]
Go in maintenance, there should be a field for the key
