### ISSUE TITLE
Set Ip address from config at ip:8084

### ISSUE THREAD

**Issue by Isaksson** [Z-Wave-Me/z-way-issues#57]
I installed Raspbian and then installed z-way the raspberry is still on dhcp, i change the settings on ip:8084 from dhcp to manual and add IP Address, Network mask, gateway IP Address and default DNS was already set so i did not change that. 
Clicked save.
This is the error message that the page show me:

Err(1.18.3): main.c: 499: The spawned process 'set_defgw.sh' has exited with code 1 and says:
The spawned process 'set_defgw.sh' has exited with code 1 and says:
The spawned process 'set_defgw.sh' has exited with code 1 and says:
The spawned process 'set_defgw.sh' has exited with code 1 and says:
The spawned process 'set_defgw.s

if i now reboot the address is still dhcp but if i check the setting on the setting page at ip:8084 the he shows me my entered IP Address and Network mask but Gateway IP address is empty.

I have tried several times but same error.
So it seems to be some problem in the function that should set the default gateway.

**Comment by PoltoS** [comment]
May be scrupts require update. These scripts are shell scripts so you can check them. We wthink this functionality not main for 8084, so it is not prior
