### ISSUE TITLE
Clear storage and single backup file

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/z-way-issues#60]

**Comment by pz1** [comment]
What does clear storage mean? I do ask this, because I do store some scripts in automation/storage, so they survive updates.

**Comment by PoltoS** [comment]
reset to default.

**Comment by PoltoS** [comment]
Done in https://github.com/Z-Wave-Me/home-automation/commit/2c53a0488eb5dd66757550237c00d27ab5a21424
