### ISSUE TITLE
Много лишних классов у устройства при запросе Json

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/z-way-issues#68]
Для любого устройства показывается много лишних классов:
<img width="428" alt="2015-10-22 14 19 18" src="https://cloud.githubusercontent.com/assets/2894860/10664042/a1fab5b2-78c8-11e5-96ae-0b9dd2927d85.png">

В реале их штук 5.
Проверил 3 разных устройства, у всех мусор, при этом в expertui отображаются только реальные

**Comment by PoltoS** [comment]
Здесь также перечислены управляемые классы, а не только поддерживаемые
