### ISSUE TITLE
Online installer does not create /opt/z-way-server directory

### ISSUE THREAD

**Issue by gderosa** [Z-Wave-Me/z-way-issues#89]
Hi,

the suggested installation is with:

``` bash
wget -q -O - razberry.z-wave.me/install | sudo bash
```

Unfortunately, on new installations, the directory `/opt/z-way-server/` is not created, and everything gets installed under `/opt/` directly. Clearly the init script does not find the files where expected and nothing works, on my system at least :blush:.

But I fixed this easily by adding a mkdir command as in the below patch:

``` diff
--- install 2015-12-30 11:28:27.998965791 +0100
+++ install.new 2015-12-30 11:30:02.188297460 +0100
@@ -55,6 +55,7 @@
    upgrade_zway="yes"
 else
    echo "z-way-server new installation"
+   mkdir -p $ZWAY_DIR
 fi

 ##### The percentage of updates #####
```

Does anyone else have the same issue?

Thanks!

**Comment by gderosa** [comment]
(I don't know which github repo the install script belongs to, I'd have sent a small pull request otherwise).

**Comment by gderosa** [comment]
(closing for now, need further checks)

**Comment by PoltoS** [comment]
thanks. fixed

**Comment by PoltoS** [comment]
no, reverted. the problem is not in this mkdir. the package (tgz) itself contains the folder, so no need to create it

**Comment by PoltoS** [comment]
add -x at the end of the install command and let's see what happens

**Comment by gderosa** [comment]
@PoltoS, I agree with the revert, and that's why I closed the issue eventually.

It may be some strange interaction in my system: I tried again and it worked without modifications...

If I find something more reproducible, I'll reopen this or open a new issue.

In the meantime, sorry for the early report :blush:
