### ISSUE TITLE
Possible bug with CC ThermostatSetpoint v3

### ISSUE THREAD

**Issue by alexus1211** [Z-Wave-Me/z-way-issues#94]
Hi,

yesterday I included a Room Thermostat from Danfoss into Z-Way. The interview was successfull except for 2 Command Classes: ThermostatSetPoint and Version. This device supports the ThermostatSetPoint V3 and if I look deep into the traces it seems there is a misinterpretation of the values delivered by the Danfoss RS.
Attached the following:
- Screenshot from Expert UI about interview
- Log from Z-Wave debug log (lines from 118 to 121 is where I suspect the issue is)
- link to the Specification of the Danfoss RS: http://products.z-wavealliance.org/products/1062

Thanks and regards

[zlog.txt](https://github.com/Z-Wave-Me/z-way-issues/files/98990/zlog.txt)
![2016-01-21 10_50_25-z-wave expert ui](https://cloud.githubusercontent.com/assets/16215643/12477479/156c4232-c030-11e5-82bd-2ab315fec3c7.png)

**Comment by PoltoS** [comment]
There are teo bugs in this devices (Danfoss was informed):
1. MultiCmd CC can not handle more than 2-3 packets.

Workaround: change in Defaults.xml number of packets from 6 to 3.
1. Device reports ThermostatSetpoint v3, but does not answer to v3 command.

Workaround: apply this patch https://github.com/Z-Wave-Me/home-automation/commit/612e5a5f14e4e89527d0cfb1015371bb56b13571 or wait for v2.2.2
