### ISSUE TITLE
Feature: Websocket server which clients can connect to and receive all ZWaveAPI events

### ISSUE THREAD

**Issue by geirgp** [Z-Wave-Me/z-way-issues#97]
I want to use my uzb1/zway as a pure zway tranceiver for my own software.

Currently you need to poll for events by calling "/ZWaveAPI/Data/_timestamp_", which is not ideal: you need a very low polling interval in order to reduce lag, this could potentionally generate a lot of traffic.

It would be a LOT better if clients could connect to a websocket server which pushes all received command classes to the client directly as they occur in real time.

Ideally this should be 2-way, so clients can also send command classes to devices through the websocket, but that is not first priority and can wait for version 2.

https://forum.z-wave.me/viewtopic.php?f=3419&t=22636&sid=0796747f72b8063e50b25633913e8c84

**Comment by pastukhov** [comment]
+1

**Comment by PoltoS** [comment]
Why not to make own module based on WS server? New manual describes how to use WS server: https://github.com/Z-Wave-Me/Z-Way-Manual/blob/master/includesDev/cap3.tex#L431

**Comment by pastukhov** [comment]
Yes, exactly what we need to do.
I see O7 repo and it looks like what we want .
