### ISSUE TITLE
JSON API over WebSockets

### ISSUE THREAD

**Issue by jagge1988** [Z-Wave-Me/z-way-issues#98]
Hi,

I have a functional system which polls the JSON API from the z-way deamon every second. But this kinda sucks. So I saw the version 2.2.0 will support WebSockets, which would be perfect. Sadly, there is no documentation in your developer docs. 

Thanks
Martin

**Comment by PoltoS** [comment]
There is a ready to go WS server on 8083. It only updates status off devices change.

Otherwose you can make your own server based on WS API. https://github.com/Z-Wave-Me/z-way-issues/issues/97
